"""update

Revision ID: 08307b7fb1e7
Revises: 95222051d9cb
Create Date: 2022-08-22 09:42:38.980232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08307b7fb1e7'
down_revision = '95222051d9cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
