"""update

Revision ID: 18d8c84da841
Revises: 977b55090583
Create Date: 2022-09-12 13:19:40.974693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d8c84da841'
down_revision = '977b55090583'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vulnerabilities_Discovered_on', table_name='vulnerabilities')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_vulnerabilities_Discovered_on', 'vulnerabilities', ['Discovered_on'], unique=False)
    # ### end Alembic commands ###
