"""update

Revision ID: 4dbd79658694
Revises: 9fb7f30c42d9
Create Date: 2022-08-23 08:11:23.190967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dbd79658694'
down_revision = '9fb7f30c42d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'usertype',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'usertype',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
