"""update

Revision ID: 977b55090583
Revises: fbc2d3a25498
Create Date: 2022-08-28 11:10:39.450997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977b55090583'
down_revision = 'fbc2d3a25498'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan', sa.Column('main_domain', sa.String(), nullable=True))
    op.add_column('scan', sa.Column('scan_name', sa.String(), nullable=True))
    op.drop_index('ix_scan_domain', table_name='scan')
    op.drop_index('ix_scan_name', table_name='scan')
    op.drop_index('ix_scan_template_used', table_name='scan')
    op.create_index(op.f('ix_scan_main_domain'), 'scan', ['main_domain'], unique=False)
    op.create_index(op.f('ix_scan_scan_name'), 'scan', ['scan_name'], unique=False)
    op.drop_column('scan', 'template_used')
    op.drop_column('scan', 'name')
    op.drop_column('scan', 'domain')
    op.add_column('vulnerabilities', sa.Column('template_used', sa.String(), nullable=True))
    op.create_index(op.f('ix_vulnerabilities_template_used'), 'vulnerabilities', ['template_used'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnerabilities_template_used'), table_name='vulnerabilities')
    op.drop_column('vulnerabilities', 'template_used')
    op.add_column('scan', sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('scan', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('scan', sa.Column('template_used', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_scan_scan_name'), table_name='scan')
    op.drop_index(op.f('ix_scan_main_domain'), table_name='scan')
    op.create_index('ix_scan_template_used', 'scan', ['template_used'], unique=False)
    op.create_index('ix_scan_name', 'scan', ['name'], unique=False)
    op.create_index('ix_scan_domain', 'scan', ['domain'], unique=False)
    op.drop_column('scan', 'scan_name')
    op.drop_column('scan', 'main_domain')
    # ### end Alembic commands ###
