"""update

Revision ID: 9fb7f30c42d9
Revises: 08307b7fb1e7
Create Date: 2022-08-22 09:44:26.606750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb7f30c42d9'
down_revision = '08307b7fb1e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'usertype',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'usertype',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
