"""update

Revision ID: a9d71c5306b6
Revises: 
Create Date: 2022-08-22 09:27:03.701749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9d71c5306b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('scan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('time_started', sa.DateTime(), nullable=True),
    sa.Column('time_finshed', sa.DateTime(), nullable=True),
    sa.Column('progress_status', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_used', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_description'), 'scan', ['description'], unique=False)
    op.create_index(op.f('ix_scan_domain'), 'scan', ['domain'], unique=False)
    op.create_index(op.f('ix_scan_id'), 'scan', ['id'], unique=False)
    op.create_index(op.f('ix_scan_progress_status'), 'scan', ['progress_status'], unique=False)
    op.create_index(op.f('ix_scan_template_used'), 'scan', ['template_used'], unique=False)
    op.create_index(op.f('ix_scan_time_finshed'), 'scan', ['time_finshed'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('des', sa.Text(), nullable=True),
    sa.Column('scan', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scan'], ['scan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_des'), 'logs', ['des'], unique=False)
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_table('vulnerabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Type', sa.String(), nullable=True),
    sa.Column('Title', sa.String(), nullable=True),
    sa.Column('Severity', sa.String(), nullable=True),
    sa.Column('CVSS_Score', sa.String(), nullable=True),
    sa.Column('CVE_CWE', sa.String(), nullable=True),
    sa.Column('Vulnerable_URL', sa.String(), nullable=True),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('Discovered_on', sa.String(), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerabilities_CVE_CWE'), 'vulnerabilities', ['CVE_CWE'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_CVSS_Score'), 'vulnerabilities', ['CVSS_Score'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_Description'), 'vulnerabilities', ['Description'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_Discovered_on'), 'vulnerabilities', ['Discovered_on'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_Severity'), 'vulnerabilities', ['Severity'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_Title'), 'vulnerabilities', ['Title'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_Type'), 'vulnerabilities', ['Type'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_Vulnerable_URL'), 'vulnerabilities', ['Vulnerable_URL'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_id'), 'vulnerabilities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnerabilities_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_Vulnerable_URL'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_Type'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_Title'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_Severity'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_Discovered_on'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_Description'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_CVSS_Score'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_CVE_CWE'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_des'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_scan_time_finshed'), table_name='scan')
    op.drop_index(op.f('ix_scan_template_used'), table_name='scan')
    op.drop_index(op.f('ix_scan_progress_status'), table_name='scan')
    op.drop_index(op.f('ix_scan_id'), table_name='scan')
    op.drop_index(op.f('ix_scan_domain'), table_name='scan')
    op.drop_index(op.f('ix_scan_description'), table_name='scan')
    op.drop_table('scan')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
