"""update

Revision ID: bac52b76c543
Revises: a9d71c5306b6
Create Date: 2022-08-22 09:29:37.175591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac52b76c543'
down_revision = 'a9d71c5306b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ver_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ver_code')
    # ### end Alembic commands ###
